In [41]:
# calling the numpy package
import numpy as np

# Ejercicio 1: Crear un array de 10 elementos con ceros.
ej_1 = np.zeros(10)
print("1. ", ej_1)

# Ejercicio 2: Genera un array con los números del 1 al 20.
ej_2 = np.arange(1, 21)
print("2. ", ej_2)

# Ejercicio 3: Crea un array con los números pares del 2 al 50.
ej_3 = np.arange(2, 51, 2)
print("3. ", ej_3)

# Ejercicio 4: Crea un array con los números pares del 2 al 50.
ej_4 = np.arange(2, 51, 2)
print("4. ", ej_4)

# Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
ej_5 = np.random.randint(0, 2, size=(4, 4)) 
print("5. ", ej_5)

# Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ej_6 = a + b
print("6. ", ej_6)

# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.
a_rnd = np.random.randint(1, 11, size=(3, 3)) 
b_rnd = np.random.randint(1, 11, size=(3, 3))
ej_7 = a_rnd * b_rnd
print("7. ", ej_7)

# Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.
ej_8 = np.random.randint(1, 101, size=(15))
print("8. El maximo es: ", ej_8.max())
print(" El minimo es: ", ej_8.min())
print(" El promedio es: ", ej_8.mean())

# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
matriz_ej9 = np.random.randint(1, 26, size=(5, 5))
ej_9 = np.diag(matriz_ej9)
print("9. ", ej_9)

# Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna
matriz_ej10 = np.random.randint(1, 21, size=(3, 5))
ej_10_columns = matriz_ej10.sum(axis=0)
ej_10_rows = matriz_ej10.sum(axis=1)
print("10. La suma de cada fila quedaria: ", ej_10_rows)
print(" La suma de cada columna quedaria: ", ej_10_columns)

1.  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2.  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
3.  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
4.  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
5.  [[1 0 1 1]
 [0 0 0 1]
 [0 1 0 1]
 [1 0 0 1]]
6.  [5 7 9]
7.  [[20  7 27]
 [ 8 10 10]
 [54 40  1]]
8. El maximo es:  100
 El minimo es:  5
 El promedio es:  54.06666666666667
9.  [18 22 20  3 17]
10. La suma de cada fila quedaria:  [35 78 47]
 La suma de cada columna quedaria:  [28 45 36 33 18]
