In [ ]:
import numpy as np
import random

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
a


array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0] = 10
a
a[4]

np.int64(5)

In [ ]:
rango = np.arange(10)
print(rango)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz[0,1]

[[1 2 3]
 [4 5 6]]


np.int64(2)

In [ ]:
np.random.seed(42)
matriz_aleatoria = np.random.rand(4, 4)
print(matriz_aleatoria)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]
